// Generated by gencpp from file lilac_fundamentals/ExecutePlan.msg
// DO NOT EDIT!


#ifndef LILAC_FUNDAMENTALS_MESSAGE_EXECUTEPLAN_H
#define LILAC_FUNDAMENTALS_MESSAGE_EXECUTEPLAN_H

#include <ros/service_traits.h>


#include <lilac_fundamentals/ExecutePlanRequest.h>
#include <lilac_fundamentals/ExecutePlanResponse.h>


namespace lilac_fundamentals
{

struct ExecutePlan
{

typedef ExecutePlanRequest Request;
typedef ExecutePlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecutePlan
} // namespace lilac_fundamentals


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lilac_fundamentals::ExecutePlan > {
  static const char* value()
  {
    return "8b63ba8f8960301ada9bc2fc61f718b7";
  }

  static const char* value(const ::lilac_fundamentals::ExecutePlan&) { return value(); }
};

template<>
struct DataType< ::lilac_fundamentals::ExecutePlan > {
  static const char* value()
  {
    return "lilac_fundamentals/ExecutePlan";
  }

  static const char* value(const ::lilac_fundamentals::ExecutePlan&) { return value(); }
};


// service_traits::MD5Sum< ::lilac_fundamentals::ExecutePlanRequest> should match 
// service_traits::MD5Sum< ::lilac_fundamentals::ExecutePlan > 
template<>
struct MD5Sum< ::lilac_fundamentals::ExecutePlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lilac_fundamentals::ExecutePlan >::value();
  }
  static const char* value(const ::lilac_fundamentals::ExecutePlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lilac_fundamentals::ExecutePlanRequest> should match 
// service_traits::DataType< ::lilac_fundamentals::ExecutePlan > 
template<>
struct DataType< ::lilac_fundamentals::ExecutePlanRequest>
{
  static const char* value()
  {
    return DataType< ::lilac_fundamentals::ExecutePlan >::value();
  }
  static const char* value(const ::lilac_fundamentals::ExecutePlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lilac_fundamentals::ExecutePlanResponse> should match 
// service_traits::MD5Sum< ::lilac_fundamentals::ExecutePlan > 
template<>
struct MD5Sum< ::lilac_fundamentals::ExecutePlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lilac_fundamentals::ExecutePlan >::value();
  }
  static const char* value(const ::lilac_fundamentals::ExecutePlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lilac_fundamentals::ExecutePlanResponse> should match 
// service_traits::DataType< ::lilac_fundamentals::ExecutePlan > 
template<>
struct DataType< ::lilac_fundamentals::ExecutePlanResponse>
{
  static const char* value()
  {
    return DataType< ::lilac_fundamentals::ExecutePlan >::value();
  }
  static const char* value(const ::lilac_fundamentals::ExecutePlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LILAC_FUNDAMENTALS_MESSAGE_EXECUTEPLAN_H
