// Generated by gencpp from file lilac_fundamentals/ExecutePlanRequest.msg
// DO NOT EDIT!


#ifndef LILAC_FUNDAMENTALS_MESSAGE_EXECUTEPLANREQUEST_H
#define LILAC_FUNDAMENTALS_MESSAGE_EXECUTEPLANREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lilac_fundamentals
{
template <class ContainerAllocator>
struct ExecutePlanRequest_
{
  typedef ExecutePlanRequest_<ContainerAllocator> Type;

  ExecutePlanRequest_()
    : plan()  {
    }
  ExecutePlanRequest_(const ContainerAllocator& _alloc)
    : plan(_alloc)  {
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _plan_type;
  _plan_type plan;


    enum { RIGHT = 0 };
     enum { UP = 1 };
     enum { LEFT = 2 };
     enum { DOWN = 3 };
 

  typedef boost::shared_ptr< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecutePlanRequest_

typedef ::lilac_fundamentals::ExecutePlanRequest_<std::allocator<void> > ExecutePlanRequest;

typedef boost::shared_ptr< ::lilac_fundamentals::ExecutePlanRequest > ExecutePlanRequestPtr;
typedef boost::shared_ptr< ::lilac_fundamentals::ExecutePlanRequest const> ExecutePlanRequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lilac_fundamentals

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'lilac_fundamentals': ['/home/liliac/lilac/src/lilac_fundamentals/msg', '/home/liliac/lilac/src/lilac_fundamentals/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b54eac5a49da859b9d3441a50111d74";
  }

  static const char* value(const ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b54eac5a49da859ULL;
  static const uint64_t static_value2 = 0xb9d3441a50111d74ULL;
};

template<class ContainerAllocator>
struct DataType< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lilac_fundamentals/ExecutePlanRequest";
  }

  static const char* value(const ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 RIGHT = 0\n\
int32 UP = 1\n\
int32 LEFT = 2\n\
int32 DOWN = 3\n\
\n\
int32[] plan\n\
";
  }

  static const char* value(const ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ExecutePlanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lilac_fundamentals::ExecutePlanRequest_<ContainerAllocator>& v)
  {
    s << indent << "plan[]" << std::endl;
    for (size_t i = 0; i < v.plan.size(); ++i)
    {
      s << indent << "  plan[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.plan[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LILAC_FUNDAMENTALS_MESSAGE_EXECUTEPLANREQUEST_H
