// Generated by gencpp from file lilac_fundamentals/MoveToPositionRequest.msg
// DO NOT EDIT!


#ifndef LILAC_FUNDAMENTALS_MESSAGE_MOVETOPOSITIONREQUEST_H
#define LILAC_FUNDAMENTALS_MESSAGE_MOVETOPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lilac_fundamentals
{
template <class ContainerAllocator>
struct MoveToPositionRequest_
{
  typedef MoveToPositionRequest_<ContainerAllocator> Type;

  MoveToPositionRequest_()
    : row(0)
    , column(0)  {
    }
  MoveToPositionRequest_(const ContainerAllocator& _alloc)
    : row(0)
    , column(0)  {
    }



   typedef int32_t _row_type;
  _row_type row;

   typedef int32_t _column_type;
  _column_type column;




  typedef boost::shared_ptr< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToPositionRequest_

typedef ::lilac_fundamentals::MoveToPositionRequest_<std::allocator<void> > MoveToPositionRequest;

typedef boost::shared_ptr< ::lilac_fundamentals::MoveToPositionRequest > MoveToPositionRequestPtr;
typedef boost::shared_ptr< ::lilac_fundamentals::MoveToPositionRequest const> MoveToPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lilac_fundamentals

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lilac_fundamentals': ['/home/liliac/lilac/src/lilac_fundamentals/msg', '/home/liliac/lilac/src/lilac_fundamentals/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f16bb40ce11ad15e58dbd12d1bf5d9bd";
  }

  static const char* value(const ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf16bb40ce11ad15eULL;
  static const uint64_t static_value2 = 0x58dbd12d1bf5d9bdULL;
};

template<class ContainerAllocator>
struct DataType< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lilac_fundamentals/MoveToPositionRequest";
  }

  static const char* value(const ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 row\n\
int32 column\n\
\n\
";
  }

  static const char* value(const ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.row);
      stream.next(m.column);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MoveToPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lilac_fundamentals::MoveToPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "row: ";
    Printer<int32_t>::stream(s, indent + "  ", v.row);
    s << indent << "column: ";
    Printer<int32_t>::stream(s, indent + "  ", v.column);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LILAC_FUNDAMENTALS_MESSAGE_MOVETOPOSITIONREQUEST_H
