// Generated by gencpp from file lilac_fundamentals/MoveToPosition.msg
// DO NOT EDIT!


#ifndef LILAC_FUNDAMENTALS_MESSAGE_MOVETOPOSITION_H
#define LILAC_FUNDAMENTALS_MESSAGE_MOVETOPOSITION_H

#include <ros/service_traits.h>


#include <lilac_fundamentals/MoveToPositionRequest.h>
#include <lilac_fundamentals/MoveToPositionResponse.h>


namespace lilac_fundamentals
{

struct MoveToPosition
{

typedef MoveToPositionRequest Request;
typedef MoveToPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveToPosition
} // namespace lilac_fundamentals


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lilac_fundamentals::MoveToPosition > {
  static const char* value()
  {
    return "5af7833001d12f0202ac6047222437e9";
  }

  static const char* value(const ::lilac_fundamentals::MoveToPosition&) { return value(); }
};

template<>
struct DataType< ::lilac_fundamentals::MoveToPosition > {
  static const char* value()
  {
    return "lilac_fundamentals/MoveToPosition";
  }

  static const char* value(const ::lilac_fundamentals::MoveToPosition&) { return value(); }
};


// service_traits::MD5Sum< ::lilac_fundamentals::MoveToPositionRequest> should match 
// service_traits::MD5Sum< ::lilac_fundamentals::MoveToPosition > 
template<>
struct MD5Sum< ::lilac_fundamentals::MoveToPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lilac_fundamentals::MoveToPosition >::value();
  }
  static const char* value(const ::lilac_fundamentals::MoveToPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lilac_fundamentals::MoveToPositionRequest> should match 
// service_traits::DataType< ::lilac_fundamentals::MoveToPosition > 
template<>
struct DataType< ::lilac_fundamentals::MoveToPositionRequest>
{
  static const char* value()
  {
    return DataType< ::lilac_fundamentals::MoveToPosition >::value();
  }
  static const char* value(const ::lilac_fundamentals::MoveToPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lilac_fundamentals::MoveToPositionResponse> should match 
// service_traits::MD5Sum< ::lilac_fundamentals::MoveToPosition > 
template<>
struct MD5Sum< ::lilac_fundamentals::MoveToPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lilac_fundamentals::MoveToPosition >::value();
  }
  static const char* value(const ::lilac_fundamentals::MoveToPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lilac_fundamentals::MoveToPositionResponse> should match 
// service_traits::DataType< ::lilac_fundamentals::MoveToPosition > 
template<>
struct DataType< ::lilac_fundamentals::MoveToPositionResponse>
{
  static const char* value()
  {
    return DataType< ::lilac_fundamentals::MoveToPosition >::value();
  }
  static const char* value(const ::lilac_fundamentals::MoveToPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LILAC_FUNDAMENTALS_MESSAGE_MOVETOPOSITION_H
