(cl:defpackage lilac_fundamentals-srv
  (:use )
  (:export
   "MOVETOPOSITION"
   "<MOVETOPOSITION-REQUEST>"
   "MOVETOPOSITION-REQUEST"
   "<MOVETOPOSITION-RESPONSE>"
   "MOVETOPOSITION-RESPONSE"
   "EXECUTEPLAN"
   "<EXECUTEPLAN-REQUEST>"
   "EXECUTEPLAN-REQUEST"
   "<EXECUTEPLAN-RESPONSE>"
   "EXECUTEPLAN-RESPONSE"
  ))

